/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrativo;

import Funcionarios.Funcionarios;
import UTIL.Conexao;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class PesquisarLivros extends javax.swing.JFrame {

    public ResultSet resultset;
    
    String titulo, autor, genero, conservacao, lancamento,idioma, editora, data;
    Double preco_compra, preco_venda;
    int quantidade;
    String tombo;
    int ntombo;
    
    int i;
    public void setTeste(int teste){
        i=teste;
    }
    
    private String cadastro_livros="";
    
    public PesquisarLivros() {
        initComponents();

        jTextField10.grabFocus();
        
        Date relogio = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        formatador.format( relogio );
        jTextField7.setText(formatador.format( relogio ));
        
        
        //desabilita botões alterar, excluir ate pesquisar o tombo do livro
        desabilitarbotao(false);
        
        //muda a cor
        jPanel1.setBackground(new Color(11,158,255));
        jButton1.setBackground(new Color(255,255,255));
        jButton2.setBackground(new Color(255,255,255));
        jButton3.setBackground(new Color(255,255,255));
        jButton4.setBackground(new Color(255,255,255));
        jButton5.setBackground(new Color(255,255,255));
        jComboBox1.setBackground(new Color(255,255,255));
        jComboBox2.setBackground(new Color(255,255,255));
    }
    
    //alterar imagem do banco de dados
    public void alterar_imagem(){
        String ntombo = tombo;
        try {
            Image img = ((ImageIcon)jLabel14.getIcon()).getImage();
                BufferedImage bi = new BufferedImage(//é a imagem na memória e que pode ser alterada
                    img.getWidth(null),
                        img.getHeight(null),
                        BufferedImage.TYPE_INT_RGB);
                Graphics2D g2 = bi.createGraphics();
                           g2.drawImage(img, 0, 0, null);
                    ByteArrayOutputStream buffer = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", buffer);
        
        Conexao con = new Conexao();
        con.conecta();
        String caminho = jLabel14.getIcon().toString();
        InputStream fis;
        File file = new File(caminho);
        fis = new FileInputStream(file);
            //*//Aqui faz update (alteração no banco)
                    PreparedStatement ps = con.conexao.prepareStatement("UPDATE cadastro_livros_fotos set foto = ? where cod = ?");
                    ps.setBytes(1, buffer.toByteArray());
                    String cod = ntombo;
                    ps.setString(2, cod);
                    ps.executeUpdate();
                    ps.close();

            fis.close();
            
            //limpar o campo da imagem apos alteração
            jLabel14.setIcon(null);
            
        } catch (IOException | SQLException ex) {
           
        }  
    }
    
    //excluir imagem do anco de dados
    public void excluir_imagem(){
        
        tombo = jTextField10.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca", "root", "");
            Statement stm = con.createStatement();
            if (stm.executeUpdate("DELETE FROM cadastro_livros_fotos WHERE cod='"+tombo+"'")!=0)
            {
                jLabel14.setIcon(null);
            }
        }
        catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de  Livros");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/alterar.png"))); // NOI18N
        jButton1.setText("Alterar Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 531, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("SAIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 533, -1, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 15, 61, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nº Tombo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 17, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("PESQUISA DE LIVROS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 339, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Titulo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 128, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 263, -1));

        jLabel2.setText("Autor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 56, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 263, -1));

        jLabel3.setText("Genero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 47, -1));

        jLabel4.setText("Estado de Conservação");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 301, 140, -1));

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, 96, -1));

        jLabel5.setText("Idioma");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 371, 86, -1));

        jLabel6.setText("Quantidade / Estoque");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 461, 129, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 493, 108, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Imagem do Livro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 61, 177, -1));

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 493, 90, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 461, 68, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesquisar.png"))); // NOI18N
        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 12, 121, -1));

        jLabel12.setText("Ano / Lançamento");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 301, 104, -1));

        jLabel13.setText("Editora do Livro");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 371, 104, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 403, 141, -1));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 87, 200, 281));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/deletar2.png"))); // NOI18N
        jButton3.setText("Excluir Cadastro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 531, 151, -1));

        try {
            jTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 333, 108, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o genero abaixo:", "Administração", "Adulto", "Contabilidade", "Espanhol", "Ficção Científica", "Física", "Geografia", "História", "Infantil", "Informática", "Inglês", "Matemática", "Português", "Química", "Revistas", "Terror" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, 181, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o idioma abaixo:", "Português", "Inglês" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesquisar.png"))); // NOI18N
        jButton5.setText("Pesquisar Todos os Livros");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, -1));

        jLabel8.setText("Valor de Compra R$:");

        jLabel9.setText("Valor de venda R$:");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesquisar.png"))); // NOI18N
        jButton6.setText("Buscar Imagem");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //desabilitar botões de ediatr, excluir e função ate pesquisar cpf
    public void desabilitarbotao(boolean condicao){
        jButton1.setEnabled(condicao);
        jButton3.setEnabled(condicao);
        jComboBox1.setEnabled(condicao);
        jComboBox2.setEnabled(condicao);
    }
    public void pesquisaimagem() throws SQLException{
        
         tombo = jTextField10.getText();
        
        Conexao con = new Conexao();
        con.conecta();
        con.executeSQLSelect("SELECT * FROM cadastro_livros_fotos where cod = '"+tombo+"'");
        con.resultset.beforeFirst();
        while(con.resultset.next()){
            //int xCod = con.resultset.getInt("cod");
            byte[] imgBytes = ((byte[]) con.resultset.getBytes("foto"));
            ImageIcon pic = null;
            pic = new ImageIcon(imgBytes);
            Image scaled = pic.getImage().getScaledInstance(jLabel14.getWidth(), jLabel14.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(scaled);
            jLabel14.setIcon(icon);//Adapta o tamanho da img para ficar do tamanho da label
  
        } 
        con.desconecta();
    }
    
    public void pesquisarlivros() {
        
       if(jTextField10.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null, "Preencha o campo nº do Tombo para proseguir!");
        }
        else
        {
            
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca", "root", "");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * FROM cadastro_livros");

            tombo = jTextField10.getText();
            
            while(res.next()) {

                if(res.getString("tombo").compareTo(tombo)==0)
                {
                  
                    jTextField1.setText(res.getString("titulo"));
                    jTextField2.setText(res.getString("autor"));
                    jComboBox1.setSelectedItem(res.getString("genero"));
                    jTextField4.setText(res.getString("conservacao"));
                    jTextField12.setText(res.getString("lancamento"));
                    jComboBox2.setSelectedItem(res.getString("idioma"));
                    jTextField13.setText(res.getString("editora"));
                    jTextField6.setText(res.getString("quantidade"));
                    jTextField7.setText(res.getString("data"));
                    jTextField8.setText(res.getString("preco_compra"));                   
                    jTextField9.setText(res.getString("preco_venda"));
   
                }
            }
   
            //habilita botões alterar, excluir apos pesquisar o tombo do livro
            desabilitarbotao(true);
        } 
        catch(ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
     }
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        if(jTextField2.getText().equals("")|| jComboBox1.getSelectedItem().equals("Selecione o genero abaixo:")|| jTextField4.getText().equals("")|| jComboBox2.getSelectedItem().equals("Selecione o idioma abaixo:")|| jTextField6.getText().equals("")|| jTextField7.getText().equals("")|| jTextField8.getText().equals("")|| jTextField9.getText().equals("")|| jTextField10.getText().equals("")|| jTextField12.getText().equals("")|| jTextField13.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null, "Preencha todos os campos para realizar a alteração!");
        }
        else
        {
            tombo = jTextField10.getText();
            titulo = jTextField1.getText();
            autor = jTextField2.getText();
            genero = (String) jComboBox1.getSelectedItem();
            conservacao = jTextField4.getText();
            lancamento = jTextField12.getText();
            idioma = (String) jComboBox2.getSelectedItem();
            editora = jTextField13.getText();
            quantidade = Integer.parseInt(jTextField6.getText());
            data = jTextField7.getText();
            preco_compra = Double.parseDouble(jTextField8.getText());
            preco_venda =Double.parseDouble(jTextField9.getText());

            try
             {
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca", "root", "");
               Statement stm = con.createStatement();
               if (stm.executeUpdate(" UPDATE cadastro_livros SET titulo='"+titulo+"',autor='"+autor+"',genero='"+genero+"',conservacao='"+conservacao+"',lancamento='"+lancamento+"',idioma='"+idioma+"',editora='"+editora+"',quantidade='"+quantidade+"',data='"+data+"',preco_compra='"+preco_compra+"',preco_venda='"+preco_venda+"' WHERE tombo='"+tombo+"'")!=0)
               {
                    JOptionPane.showMessageDialog(null,"Alteração efetuada com sucesso!!!!","Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    
                    jTextField10.setText("");
                    jComboBox1.setSelectedItem(""+"Selecione o genero abaixo:");
                    jComboBox2.setSelectedItem(""+"Selecione o idioma abaixo:");
                    
                    //desabilita botões alterar, excluir ate pesquisar o tombo do livro
                    desabilitarbotao(false);
                    jTextField10.grabFocus();
                    
                    //alterar a imagem no banco de dados
                    alterar_imagem();
               }
               else
               {
                    JOptionPane.showMessageDialog(null,"Dados não encontrados para Alteração!!!!","Atenção", JOptionPane.INFORMATION_MESSAGE);
               }
            }
               
            catch(ClassNotFoundException e) 
            {
            JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
            }
            catch(SQLException e) 
            {
                //JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
                
            }
                
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField4.setText("");
                jTextField6.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField12.setText("");
                jTextField13.setText("");
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(i==2){
            Funcionarios vFunc=new Funcionarios();
            vFunc.setVisible(true);
            dispose();
        }
        else{
            Administrativo vAdm=new Administrativo();
            vAdm.setVisible(true);
            dispose();
        }
        
        //dispose();
        //Administrativo vAdm=new Administrativo();
       // vAdm.setVisible(true);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 
        pesquisarlivros();
        try {
            pesquisaimagem();
        } catch (SQLException ex) {
            Logger.getLogger(PesquisarLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

       tombo = jTextField10.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca", "root", "");
            Statement stm = con.createStatement();
            if (stm.executeUpdate("DELETE FROM cadastro_livros WHERE tombo='"+tombo+"'")!=0)
            {
                JOptionPane.showMessageDialog(null,"Cadastro Removido com sucesso!!!!","Sucesso", JOptionPane.INFORMATION_MESSAGE);

            tombo = jTextField10.getText();
            titulo = jTextField1.getText();
            autor = jTextField2.getText();
            genero = (String) jComboBox1.getSelectedItem();
            conservacao = jTextField4.getText();
            lancamento = jTextField12.getText();
            idioma = (String) jComboBox2.getSelectedItem();
            editora = jTextField13.getText();
            quantidade = Integer.parseInt(jTextField6.getText());
            data = jTextField7.getText();
            preco_compra = Double.parseDouble(jTextField8.getText());
            preco_venda =Double.parseDouble(jTextField9.getText());
            jComboBox1.setSelectedItem(""+"Selecione o genero abaixo:");
            jComboBox2.setSelectedItem(""+"Selecione o idioma abaixo:");
            
            //desabilita botões alterar, excluir ate pesquisar o tombo do livro
            desabilitarbotao(false);
            jTextField10.grabFocus();
            
            //excluir imagem do banco e limpar o Jlabel
            excluir_imagem();
            }
            
        }
        catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField4.setText("");
                jTextField6.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField12.setText("");
                jTextField13.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PesquisaLivrosAvancada vPesq=new PesquisaLivrosAvancada();
        vPesq.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        try {
            JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File("/Livraria_WhatsBook_15_11_18_3/img/"));
            file.setDialogTitle("Carregar Imagem da Pessoa");
            file.showOpenDialog(this);
            jLabel14.setIcon(new ImageIcon(file.getSelectedFile().getPath()));
        }catch(Exception e){
            jLabel14.setIcon(new ImageIcon("C:\\Livraria_WhatsBook_15_11_18_3\\img\\semfoto.jpg"));
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PesquisarLivros().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JFormattedTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

   
}
